// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7KuJwicI0fchCi6eVbyVcQs1mdhYy8A',
    appId: '1:231469069165:web:4d359dfee92f8d08696064',
    messagingSenderId: '231469069165',
    projectId: 'tes1-3438b',
    authDomain: 'tes1-3438b.firebaseapp.com',
    storageBucket: 'tes1-3438b.appspot.com',
    measurementId: 'G-1H90QZ3S52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcrao4QpvSaL7baT2QX6nY9sCaxqArAGE',
    appId: '1:231469069165:android:39b2296bf4e73eef696064',
    messagingSenderId: '231469069165',
    projectId: 'tes1-3438b',
    storageBucket: 'tes1-3438b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg67OqJ8mCVZVyKU4J8T2IBR46JOwD38Q',
    appId: '1:231469069165:ios:14c1d9f3e20fccb5696064',
    messagingSenderId: '231469069165',
    projectId: 'tes1-3438b',
    storageBucket: 'tes1-3438b.appspot.com',
    iosBundleId: 'com.example.latihan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg67OqJ8mCVZVyKU4J8T2IBR46JOwD38Q',
    appId: '1:231469069165:ios:3ff5167741455f83696064',
    messagingSenderId: '231469069165',
    projectId: 'tes1-3438b',
    storageBucket: 'tes1-3438b.appspot.com',
    iosBundleId: 'com.example.latihan.RunnerTests',
  );
}
